version: "{build}"

image: Visual Studio 2019

skip_tags: true
clone_depth: 1

configuration: Release
platform: Any CPU

before_build:
  - nuget restore src/Microsoft.Extensions.Configuration.Etcd.sln

build:
  project: src/Microsoft.Extensions.Configuration.Etcd.sln
  publish_nuget: true
  use_snupkg_format: true
  parallel: true
  verbosity: minimal

test:
  categories:
    except:
      - Integration
